POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "Otra nota mas",
    "important": true,
    "userId": "640e35e8536050d96167e7e7"
}


# POST https://bootcamp-notes.up.railway.app/api/notes
# Content-Type: application/json

# {
#     "content": "Este cliente REST esta de puta madre",
#     "important": false
# }